### PR TITLE
Update terminal.md

### PR DESCRIPTION
**Pull request by woodenshoe-wi**
I guess I need a separate pull request for the wiki branch.

### CODE REVIEW

**Comment by woodenshoe-wi** [comment]
@01micko I moved the wiki from the wiki branch to a separate gtkdialog.wiki
repo to be compatible with how GitHub handles wikis, but I don't know how to issue a pull request for a wiki.

You should be able to clone the wiki with`git clone https://github.com/woodenshoe-wi/gtkdialog.wiki.git` and push it to your account after changing the remote.

**Comment by 01micko** [comment]
Darn, I tried the co-author thing and didn't work.

I am going to fork this over to puppylinux and close then reopen my fork like what you did with rox.

**Comment by woodenshoe-wi** [comment]
I closed this pull request when I realized that the way GitHub handles the wiki is in a separate repo, not a branch named wiki.

Have you tried `git clone https://github.com/woodenshoe-wi/gtkdialog.wiki.git` and pushing it to puppylinux-woof-CE/gtkdialog.wiki.git?  Maybe you have to create the wiki first?

If creating the wiki makes an initial commit, it might be necessary to force push the wiki repo the first time to overwrite the initial commit.

**Comment by woodenshoe-wi** [comment]
On second thought, maybe it would work better to make the wiki in puppylinux-woof-CE/gtkdialog first.  Clone that locally `git clone https://github.com/puppylinux-woof-CE/gtkdialog.wiki.git` and then add my wiki as a remote, `git remote add woodenshoe-wi https://github.com/woodenshoe-wi/gtkdialog.wiki.git`

There still will probably be an issue with pushing my changes over the initial commit of the puppylinux-woof-CE/gtkdialog wiki, so it will probably be necessary to force push it.

**Comment by 01micko** [comment]
I just copied over you `Home.md` and pushed. Seems to be working ok. Thanks

**Pull request closed without merging**
